"""
Datos de simulación para el sistema cuando MongoDB no está disponible
o para pruebas y desarrollo
"""
from datetime import datetime, timedelta
from typing import List, Dict

class MockData:
    """Clase que proporciona datos de simulación para el sistema"""
    
    @staticmethod
    def get_mock_ofertas() -> List[Dict]:
        """Retorna una lista de ofertas de prueba"""
        fecha_base = datetime.now()
        
        return [
            {
                '_id': 'mock_001',
                'id': 'mock_001',
                'titulo_oferta': 'Desarrollador Python - Remoto',
                'empresa': 'Tech Solutions Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Desarrollador Python',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'python, flask, mongodb, git',
                'responsabilidades_breve': 'Desarrollo de aplicaciones web con Flask, mantenimiento de APIs REST, trabajo con bases de datos NoSQL.',
                'modalidad': 'Remoto',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 3,500 - S/ 4,500',
                'fecha_publicacion': (fecha_base - timedelta(days=2)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: rrhh@techsolutions.com.pe',
                'url_oferta': 'https://example.com/oferta/001',
                'documentos_requeridos': 'CV actualizado, carta de presentación',
                'contacto': 'rrhh@techsolutions.com.pe',
                'etiquetas': 'computrabajo, tacna, python, desarrollo',
                'fuente': 'Computrabajo',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=2)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=1)).isoformat()
            },
            {
                '_id': 'mock_002',
                'id': 'mock_002',
                'titulo_oferta': 'Asistente Administrativo',
                'empresa': 'Empresa Comercial Tacna S.A.C.',
                'nivel_academico': 'Bachiller',
                'puesto': 'Asistente Administrativo',
                'experiencia_minima_anios': '1 año',
                'conocimientos_clave': 'excel, word, office, atención al cliente',
                'responsabilidades_breve': 'Apoyo en labores administrativas, manejo de documentación, atención al cliente, archivo y organización.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,200 - S/ 1,500',
                'fecha_publicacion': (fecha_base - timedelta(days=1)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://example.com/oferta/002',
                'url_oferta': 'https://example.com/oferta/002',
                'documentos_requeridos': 'CV actualizado',
                'contacto': 'rrhh@comercialtacna.com',
                'etiquetas': 'bumeran, tacna, administrativo',
                'fuente': 'Bumeran',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=1)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=1)).isoformat()
            },
            {
                '_id': 'mock_003',
                'id': 'mock_003',
                'titulo_oferta': 'Practicante de Ingeniería de Sistemas',
                'empresa': 'Sistema Informático Regional',
                'nivel_academico': 'Practicante',
                'puesto': 'Practicante de Ingeniería',
                'experiencia_minima_anios': 'Sin experiencia',
                'conocimientos_clave': 'programación, bases de datos, desarrollo web',
                'responsabilidades_breve': 'Apoyo en desarrollo de software, mantenimiento de sistemas, documentación técnica.',
                'modalidad': 'Híbrido',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 800 - S/ 1,000',
                'fecha_publicacion': fecha_base.strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: practicantes@sir.com.pe',
                'url_oferta': 'https://example.com/oferta/003',
                'documentos_requeridos': 'CV, certificado de estudios',
                'contacto': 'practicantes@sir.com.pe',
                'etiquetas': 'indeed, tacna, practicante, ingeniería',
                'fuente': 'Indeed',
                'fecha_estimacion': False,
                'created_at': fecha_base.isoformat(),
                'updated_at': fecha_base.isoformat()
            },
            {
                '_id': 'mock_004',
                'id': 'mock_004',
                'titulo_oferta': 'Contador Público',
                'empresa': 'Estudio Contable Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Contador Público',
                'experiencia_minima_anios': '3 años',
                'conocimientos_clave': 'contabilidad, tributación, excel, sap',
                'responsabilidades_breve': 'Elaboración de estados financieros, declaraciones tributarias, asesoría contable y fiscal.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 2,500 - S/ 3,200',
                'fecha_publicacion': (fecha_base - timedelta(days=3)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://example.com/oferta/004',
                'url_oferta': 'https://example.com/oferta/004',
                'documentos_requeridos': 'CV, título profesional, colegiatura',
                'contacto': 'rrhh@estudiocontable.com',
                'etiquetas': 'trabajos.pe, tacna, contabilidad',
                'fuente': 'Trabajos.pe',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=3)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=2)).isoformat()
            },
            {
                '_id': 'mock_005',
                'id': 'mock_005',
                'titulo_oferta': 'Diseñador Gráfico',
                'empresa': 'Agencia Creativa Tacna',
                'nivel_academico': 'Bachiller',
                'puesto': 'Diseñador Gráfico',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'photoshop, illustrator, diseño gráfico, branding',
                'responsabilidades_breve': 'Diseño de material gráfico, identidad corporativa, publicidad digital, edición de imágenes.',
                'modalidad': 'Híbrido',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,800 - S/ 2,300',
                'fecha_publicacion': (fecha_base - timedelta(days=5)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar portafolio a: diseño@creativatacna.com',
                'url_oferta': 'https://example.com/oferta/005',
                'documentos_requeridos': 'CV, portafolio digital',
                'contacto': 'diseño@creativatacna.com',
                'etiquetas': 'computrabajo, tacna, diseño',
                'fuente': 'Computrabajo',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=5)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=4)).isoformat()
            },
            {
                '_id': 'mock_006',
                'id': 'mock_006',
                'titulo_oferta': 'Enfermera/o',
                'empresa': 'Clínica San José Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Enfermera/o',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'enfermería, salud, atención al paciente',
                'responsabilidades_breve': 'Atención de pacientes, administración de medicamentos, apoyo en procedimientos médicos.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 2,000 - S/ 2,500',
                'fecha_publicacion': (fecha_base - timedelta(days=4)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://example.com/oferta/006',
                'url_oferta': 'https://example.com/oferta/006',
                'documentos_requeridos': 'CV, título profesional, colegiatura',
                'contacto': 'rrhh@clinicasanjose.com',
                'etiquetas': 'bumeran, tacna, salud, enfermería',
                'fuente': 'Bumeran',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=4)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=3)).isoformat()
            },
            {
                '_id': 'mock_007',
                'id': 'mock_007',
                'titulo_oferta': 'Vendedor/a',
                'empresa': 'Tienda Retail Tacna',
                'nivel_academico': 'Bachiller',
                'puesto': 'Vendedor/a',
                'experiencia_minima_anios': '1 año',
                'conocimientos_clave': 'ventas, atención al cliente, comunicación',
                'responsabilidades_breve': 'Atención al cliente, venta de productos, manejo de caja, reposición de mercadería.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,000 - S/ 1,300',
                'fecha_publicacion': (fecha_base - timedelta(days=6)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en tienda o enviar CV',
                'url_oferta': 'https://example.com/oferta/007',
                'documentos_requeridos': 'CV actualizado',
                'contacto': 'rrhh@retailtacna.com',
                'etiquetas': 'indeed, tacna, ventas',
                'fuente': 'Indeed',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=6)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=5)).isoformat()
            },
            {
                '_id': 'mock_008',
                'id': 'mock_008',
                'titulo_oferta': 'Ingeniero de Sistemas',
                'empresa': 'Empresa Tecnológica Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Ingeniero de Sistemas',
                'experiencia_minima_anios': '3 años',
                'conocimientos_clave': 'java, python, sql, desarrollo web, linux',
                'responsabilidades_breve': 'Desarrollo de software, administración de servidores, diseño de sistemas, mantenimiento de infraestructura.',
                'modalidad': 'Híbrido',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 3,800 - S/ 4,500',
                'fecha_publicacion': (fecha_base - timedelta(days=7)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: sistemas@tecnologicatacna.com',
                'url_oferta': 'https://example.com/oferta/008',
                'documentos_requeridos': 'CV, título profesional',
                'contacto': 'sistemas@tecnologicatacna.com',
                'etiquetas': 'trabajos.pe, tacna, ingeniería, sistemas',
                'fuente': 'Trabajos.pe',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=7)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=6)).isoformat()
            },
            {
                '_id': 'mock_009',
                'id': 'mock_009',
                'titulo_oferta': 'Asistente de Recursos Humanos',
                'empresa': 'Consultora RRHH Tacna',
                'nivel_academico': 'Bachiller',
                'puesto': 'Asistente de RRHH',
                'experiencia_minima_anios': '1 año',
                'conocimientos_clave': 'recursos humanos, selección, capacitación, excel',
                'responsabilidades_breve': 'Apoyo en procesos de selección, gestión de personal, elaboración de documentos laborales.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,400 - S/ 1,700',
                'fecha_publicacion': (fecha_base - timedelta(days=8)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://example.com/oferta/009',
                'url_oferta': 'https://example.com/oferta/009',
                'documentos_requeridos': 'CV actualizado',
                'contacto': 'rrhh@consultorarrhh.com',
                'etiquetas': 'computrabajo, tacna, rrhh',
                'fuente': 'Computrabajo',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=8)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=7)).isoformat()
            },
            {
                '_id': 'mock_010',
                'id': 'mock_010',
                'titulo_oferta': 'Marketing Digital',
                'empresa': 'Agencia Digital Tacna',
                'nivel_academico': 'Bachiller',
                'puesto': 'Especialista en Marketing Digital',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'marketing digital, redes sociales, seo, google ads',
                'responsabilidades_breve': 'Gestión de redes sociales, campañas publicitarias digitales, análisis de métricas, creación de contenido.',
                'modalidad': 'Remoto',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 2,200 - S/ 2,800',
                'fecha_publicacion': (fecha_base - timedelta(days=9)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: marketing@digitaltacna.com',
                'url_oferta': 'https://example.com/oferta/010',
                'documentos_requeridos': 'CV, portafolio de campañas',
                'contacto': 'marketing@digitaltacna.com',
                'etiquetas': 'bumeran, tacna, marketing',
                'fuente': 'Bumeran',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=9)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=8)).isoformat()
            },
            {
                '_id': 'mock_011',
                'id': 'mock_011',
                'titulo_oferta': 'Analista de Sistemas',
                'empresa': 'Corporación Tecnológica del Sur',
                'nivel_academico': 'Profesional',
                'puesto': 'Analista de Sistemas',
                'experiencia_minima_anios': '3 años',
                'conocimientos_clave': 'análisis de sistemas, sql, uml, metodologías ágiles',
                'responsabilidades_breve': 'Análisis de requerimientos, diseño de soluciones, documentación técnica, coordinación con equipos de desarrollo.',
                'modalidad': 'Híbrido',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 3,200 - S/ 4,000',
                'fecha_publicacion': (fecha_base - timedelta(days=10)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: analisis@corptecsur.com',
                'url_oferta': 'https://pe.computrabajo.com/oferta/011',
                'documentos_requeridos': 'CV, título profesional',
                'contacto': 'analisis@corptecsur.com',
                'etiquetas': 'computrabajo, tacna, análisis, sistemas',
                'fuente': 'Computrabajo',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=10)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=9)).isoformat()
            },
            {
                '_id': 'mock_012',
                'id': 'mock_012',
                'titulo_oferta': 'Cajero/a',
                'empresa': 'Supermercado El Ahorro',
                'nivel_academico': 'Bachiller',
                'puesto': 'Cajero/a',
                'experiencia_minima_anios': '6 meses',
                'conocimientos_clave': 'atención al cliente, manejo de caja, matemáticas básicas',
                'responsabilidades_breve': 'Atención al cliente en caja, cobro de productos, manejo de efectivo y tarjetas, reposición de productos.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,000 - S/ 1,200',
                'fecha_publicacion': (fecha_base - timedelta(days=11)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://www.bumeran.com.pe/oferta/012',
                'url_oferta': 'https://www.bumeran.com.pe/oferta/012',
                'documentos_requeridos': 'CV actualizado',
                'contacto': 'rrhh@superahorro.com',
                'etiquetas': 'bumeran, tacna, cajero, ventas',
                'fuente': 'Bumeran',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=11)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=10)).isoformat()
            },
            {
                '_id': 'mock_013',
                'id': 'mock_013',
                'titulo_oferta': 'Ingeniero Civil',
                'empresa': 'Constructora Tacna S.A.',
                'nivel_academico': 'Profesional',
                'puesto': 'Ingeniero Civil',
                'experiencia_minima_anios': '4 años',
                'conocimientos_clave': 'ingeniería civil, autocad, construcción, gestión de proyectos',
                'responsabilidades_breve': 'Supervisión de obras, diseño de estructuras, planificación de proyectos, control de calidad.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 4,000 - S/ 5,000',
                'fecha_publicacion': (fecha_base - timedelta(days=12)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: ingenieria@constructacna.com',
                'url_oferta': 'https://pe.indeed.com/oferta/013',
                'documentos_requeridos': 'CV, título profesional, colegiatura',
                'contacto': 'ingenieria@constructacna.com',
                'etiquetas': 'indeed, tacna, ingeniería, construcción',
                'fuente': 'Indeed',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=12)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=11)).isoformat()
            },
            {
                '_id': 'mock_014',
                'id': 'mock_014',
                'titulo_oferta': 'Secretaria/o Ejecutiva',
                'empresa': 'Oficina Legal Tacna',
                'nivel_academico': 'Bachiller',
                'puesto': 'Secretaria/o Ejecutiva',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'office, redacción, organización, atención telefónica',
                'responsabilidades_breve': 'Atención telefónica, agenda de citas, redacción de documentos, archivo, apoyo administrativo.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,300 - S/ 1,600',
                'fecha_publicacion': (fecha_base - timedelta(days=13)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://www.trabajos.pe/oferta/014',
                'url_oferta': 'https://www.trabajos.pe/oferta/014',
                'documentos_requeridos': 'CV actualizado',
                'contacto': 'rrhh@oficinalegal.com',
                'etiquetas': 'trabajos.pe, tacna, secretaria, administrativo',
                'fuente': 'Trabajos.pe',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=13)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=12)).isoformat()
            },
            {
                '_id': 'mock_015',
                'id': 'mock_015',
                'titulo_oferta': 'Desarrollador Full Stack',
                'empresa': 'Startup Tech Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Desarrollador Full Stack',
                'experiencia_minima_anios': '3 años',
                'conocimientos_clave': 'javascript, react, node.js, mongodb, express',
                'responsabilidades_breve': 'Desarrollo de aplicaciones web completas, frontend y backend, integración de APIs, optimización de rendimiento.',
                'modalidad': 'Remoto',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 4,500 - S/ 5,500',
                'fecha_publicacion': (fecha_base - timedelta(days=1)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: dev@startuptech.com',
                'url_oferta': 'https://pe.computrabajo.com/oferta/015',
                'documentos_requeridos': 'CV, portafolio de proyectos',
                'contacto': 'dev@startuptech.com',
                'etiquetas': 'computrabajo, tacna, full stack, desarrollo',
                'fuente': 'Computrabajo',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=1)).isoformat(),
                'updated_at': fecha_base.isoformat()
            },
            {
                '_id': 'mock_016',
                'id': 'mock_016',
                'titulo_oferta': 'Médico General',
                'empresa': 'Centro Médico Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Médico General',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'medicina general, diagnóstico, atención al paciente',
                'responsabilidades_breve': 'Atención médica a pacientes, diagnóstico, prescripción de tratamientos, seguimiento de casos.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 5,000 - S/ 6,500',
                'fecha_publicacion': (fecha_base - timedelta(days=14)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: medicina@centromedico.com',
                'url_oferta': 'https://www.bumeran.com.pe/oferta/016',
                'documentos_requeridos': 'CV, título profesional, colegiatura, certificados',
                'contacto': 'medicina@centromedico.com',
                'etiquetas': 'bumeran, tacna, medicina, salud',
                'fuente': 'Bumeran',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=14)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=13)).isoformat()
            },
            {
                '_id': 'mock_017',
                'id': 'mock_017',
                'titulo_oferta': 'Practicante de Contabilidad',
                'empresa': 'Estudio Contable Integral',
                'nivel_academico': 'Practicante',
                'puesto': 'Practicante de Contabilidad',
                'experiencia_minima_anios': 'Sin experiencia',
                'conocimientos_clave': 'contabilidad básica, excel, office',
                'responsabilidades_breve': 'Apoyo en labores contables, registro de documentos, archivo, elaboración de reportes básicos.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 900 - S/ 1,100',
                'fecha_publicacion': (fecha_base - timedelta(days=15)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://pe.indeed.com/oferta/017',
                'url_oferta': 'https://pe.indeed.com/oferta/017',
                'documentos_requeridos': 'CV, certificado de estudios',
                'contacto': 'practicantes@contableintegral.com',
                'etiquetas': 'indeed, tacna, practicante, contabilidad',
                'fuente': 'Indeed',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=15)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=14)).isoformat()
            },
            {
                '_id': 'mock_018',
                'id': 'mock_018',
                'titulo_oferta': 'Chef de Cocina',
                'empresa': 'Restaurante La Casona',
                'nivel_academico': 'Bachiller',
                'puesto': 'Chef de Cocina',
                'experiencia_minima_anios': '3 años',
                'conocimientos_clave': 'cocina, gastronomía, gestión de cocina, menús',
                'responsabilidades_breve': 'Preparación de platos, diseño de menús, supervisión de cocina, control de calidad e higiene.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 2,000 - S/ 2,500',
                'fecha_publicacion': (fecha_base - timedelta(days=16)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://www.trabajos.pe/oferta/018',
                'url_oferta': 'https://www.trabajos.pe/oferta/018',
                'documentos_requeridos': 'CV, certificados de cursos',
                'contacto': 'rrhh@lacasona.com',
                'etiquetas': 'trabajos.pe, tacna, gastronomía, chef',
                'fuente': 'Trabajos.pe',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=16)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=15)).isoformat()
            },
            {
                '_id': 'mock_019',
                'id': 'mock_019',
                'titulo_oferta': 'Técnico en Redes',
                'empresa': 'Servicios Informáticos Tacna',
                'nivel_academico': 'Bachiller',
                'puesto': 'Técnico en Redes',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'redes, cisco, servidores, linux, troubleshooting',
                'responsabilidades_breve': 'Mantenimiento de redes, configuración de equipos, soporte técnico, resolución de incidencias.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 2,200 - S/ 2,800',
                'fecha_publicacion': (fecha_base - timedelta(days=17)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: redes@serviciosinfo.com',
                'url_oferta': 'https://pe.computrabajo.com/oferta/019',
                'documentos_requeridos': 'CV, certificaciones técnicas',
                'contacto': 'redes@serviciosinfo.com',
                'etiquetas': 'computrabajo, tacna, redes, técnico',
                'fuente': 'Computrabajo',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=17)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=16)).isoformat()
            },
            {
                '_id': 'mock_020',
                'id': 'mock_020',
                'titulo_oferta': 'Psicóloga/o',
                'empresa': 'Centro de Salud Mental Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Psicóloga/o',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'psicología, terapia, evaluación psicológica',
                'responsabilidades_breve': 'Atención psicológica, evaluación de pacientes, terapia individual y grupal, elaboración de informes.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 2,500 - S/ 3,200',
                'fecha_publicacion': (fecha_base - timedelta(days=18)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://www.bumeran.com.pe/oferta/020',
                'url_oferta': 'https://www.bumeran.com.pe/oferta/020',
                'documentos_requeridos': 'CV, título profesional, colegiatura',
                'contacto': 'rrhh@saludmental.com',
                'etiquetas': 'bumeran, tacna, psicología, salud',
                'fuente': 'Bumeran',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=18)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=17)).isoformat()
            },
            {
                '_id': 'mock_021',
                'id': 'mock_021',
                'titulo_oferta': 'Asistente de Marketing',
                'empresa': 'Agencia Publicitaria Tacna',
                'nivel_academico': 'Bachiller',
                'puesto': 'Asistente de Marketing',
                'experiencia_minima_anios': '1 año',
                'conocimientos_clave': 'marketing, redes sociales, diseño básico, comunicación',
                'responsabilidades_breve': 'Apoyo en campañas publicitarias, gestión de redes sociales, creación de contenido, análisis de métricas.',
                'modalidad': 'Híbrido',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,500 - S/ 1,900',
                'fecha_publicacion': (fecha_base - timedelta(days=19)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: marketing@publicitacna.com',
                'url_oferta': 'https://pe.indeed.com/oferta/021',
                'documentos_requeridos': 'CV actualizado',
                'contacto': 'marketing@publicitacna.com',
                'etiquetas': 'indeed, tacna, marketing, publicidad',
                'fuente': 'Indeed',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=19)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=18)).isoformat()
            },
            {
                '_id': 'mock_022',
                'id': 'mock_022',
                'titulo_oferta': 'Abogado/a',
                'empresa': 'Bufete Jurídico Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Abogado/a',
                'experiencia_minima_anios': '3 años',
                'conocimientos_clave': 'derecho, litigios, asesoría legal, redacción jurídica',
                'responsabilidades_breve': 'Asesoría legal, representación de clientes, redacción de documentos jurídicos, litigios.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 3,500 - S/ 4,500',
                'fecha_publicacion': (fecha_base - timedelta(days=20)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://www.trabajos.pe/oferta/022',
                'url_oferta': 'https://www.trabajos.pe/oferta/022',
                'documentos_requeridos': 'CV, título profesional, colegiatura',
                'contacto': 'rrhh@bufetejuridico.com',
                'etiquetas': 'trabajos.pe, tacna, derecho, abogado',
                'fuente': 'Trabajos.pe',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=20)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=19)).isoformat()
            },
            {
                '_id': 'mock_023',
                'id': 'mock_023',
                'titulo_oferta': 'Operador de Maquinaria Pesada',
                'empresa': 'Constructora del Sur',
                'nivel_academico': 'Bachiller',
                'puesto': 'Operador de Maquinaria',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'maquinaria pesada, excavadora, cargador frontal, seguridad',
                'responsabilidades_breve': 'Operación de maquinaria pesada, mantenimiento básico, cumplimiento de normas de seguridad.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 2,500 - S/ 3,000',
                'fecha_publicacion': (fecha_base - timedelta(days=21)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: operaciones@constructsur.com',
                'url_oferta': 'https://pe.computrabajo.com/oferta/023',
                'documentos_requeridos': 'CV, licencia de conducir, certificados',
                'contacto': 'operaciones@constructsur.com',
                'etiquetas': 'computrabajo, tacna, construcción, maquinaria',
                'fuente': 'Computrabajo',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=21)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=20)).isoformat()
            },
            {
                '_id': 'mock_024',
                'id': 'mock_024',
                'titulo_oferta': 'Nutricionista',
                'empresa': 'Clínica Nutricional Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Nutricionista',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'nutrición, dietética, evaluación nutricional',
                'responsabilidades_breve': 'Evaluación nutricional, diseño de planes alimentarios, seguimiento de pacientes, educación nutricional.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 2,200 - S/ 2,800',
                'fecha_publicacion': (fecha_base - timedelta(days=22)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://www.bumeran.com.pe/oferta/024',
                'url_oferta': 'https://www.bumeran.com.pe/oferta/024',
                'documentos_requeridos': 'CV, título profesional, colegiatura',
                'contacto': 'rrhh@nutricionaltacna.com',
                'etiquetas': 'bumeran, tacna, nutrición, salud',
                'fuente': 'Bumeran',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=22)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=21)).isoformat()
            },
            {
                '_id': 'mock_025',
                'id': 'mock_025',
                'titulo_oferta': 'Técnico en Mantenimiento',
                'empresa': 'Servicios de Mantenimiento Integral',
                'nivel_academico': 'Bachiller',
                'puesto': 'Técnico en Mantenimiento',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'mantenimiento, electricidad, plomería, aire acondicionado',
                'responsabilidades_breve': 'Mantenimiento preventivo y correctivo, reparaciones eléctricas y de plomería, instalaciones.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,800 - S/ 2,200',
                'fecha_publicacion': (fecha_base - timedelta(days=23)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: mantenimiento@serviciosintegral.com',
                'url_oferta': 'https://pe.indeed.com/oferta/025',
                'documentos_requeridos': 'CV, certificados técnicos',
                'contacto': 'mantenimiento@serviciosintegral.com',
                'etiquetas': 'indeed, tacna, mantenimiento, técnico',
                'fuente': 'Indeed',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=23)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=22)).isoformat()
            },
            {
                '_id': 'mock_026',
                'id': 'mock_026',
                'titulo_oferta': 'Asistente de Farmacia',
                'empresa': 'Farmacia San Martín',
                'nivel_academico': 'Bachiller',
                'puesto': 'Asistente de Farmacia',
                'experiencia_minima_anios': '1 año',
                'conocimientos_clave': 'farmacia, medicamentos, atención al cliente',
                'responsabilidades_breve': 'Atención al cliente, dispensación de medicamentos, control de inventario, asesoría farmacéutica básica.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,200 - S/ 1,500',
                'fecha_publicacion': (fecha_base - timedelta(days=24)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://www.trabajos.pe/oferta/026',
                'url_oferta': 'https://www.trabajos.pe/oferta/026',
                'documentos_requeridos': 'CV actualizado',
                'contacto': 'rrhh@farmaciasanmartin.com',
                'etiquetas': 'trabajos.pe, tacna, farmacia, salud',
                'fuente': 'Trabajos.pe',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=24)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=23)).isoformat()
            },
            {
                '_id': 'mock_027',
                'id': 'mock_027',
                'titulo_oferta': 'Desarrollador Mobile',
                'empresa': 'App Development Tacna',
                'nivel_academico': 'Profesional',
                'puesto': 'Desarrollador Mobile',
                'experiencia_minima_anios': '2 años',
                'conocimientos_clave': 'react native, flutter, android, ios, javascript',
                'responsabilidades_breve': 'Desarrollo de aplicaciones móviles, diseño de interfaces, integración de APIs, publicación en stores.',
                'modalidad': 'Remoto',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 4,000 - S/ 5,000',
                'fecha_publicacion': (fecha_base - timedelta(days=3)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: mobile@appdev.com',
                'url_oferta': 'https://pe.computrabajo.com/oferta/027',
                'documentos_requeridos': 'CV, portafolio de apps',
                'contacto': 'mobile@appdev.com',
                'etiquetas': 'computrabajo, tacna, mobile, desarrollo',
                'fuente': 'Computrabajo',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=3)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=2)).isoformat()
            },
            {
                '_id': 'mock_028',
                'id': 'mock_028',
                'titulo_oferta': 'Asistente de Logística',
                'empresa': 'Transportes Tacna Express',
                'nivel_academico': 'Bachiller',
                'puesto': 'Asistente de Logística',
                'experiencia_minima_anios': '1 año',
                'conocimientos_clave': 'logística, almacén, inventario, excel',
                'responsabilidades_breve': 'Control de inventario, coordinación de envíos, seguimiento de pedidos, gestión de almacén.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,400 - S/ 1,700',
                'fecha_publicacion': (fecha_base - timedelta(days=25)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://www.bumeran.com.pe/oferta/028',
                'url_oferta': 'https://www.bumeran.com.pe/oferta/028',
                'documentos_requeridos': 'CV actualizado',
                'contacto': 'logistica@tacnaexpress.com',
                'etiquetas': 'bumeran, tacna, logística, transporte',
                'fuente': 'Bumeran',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=25)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=24)).isoformat()
            },
            {
                '_id': 'mock_029',
                'id': 'mock_029',
                'titulo_oferta': 'Arquitecto/a',
                'empresa': 'Estudio de Arquitectura Moderna',
                'nivel_academico': 'Profesional',
                'puesto': 'Arquitecto/a',
                'experiencia_minima_anios': '3 años',
                'conocimientos_clave': 'arquitectura, autocad, diseño, proyectos',
                'responsabilidades_breve': 'Diseño arquitectónico, elaboración de planos, supervisión de obras, gestión de proyectos.',
                'modalidad': 'Híbrido',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 3,800 - S/ 4,800',
                'fecha_publicacion': (fecha_base - timedelta(days=26)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Enviar CV a: arquitectura@moderna.com',
                'url_oferta': 'https://pe.indeed.com/oferta/029',
                'documentos_requeridos': 'CV, título profesional, portafolio',
                'contacto': 'arquitectura@moderna.com',
                'etiquetas': 'indeed, tacna, arquitectura, diseño',
                'fuente': 'Indeed',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=26)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=25)).isoformat()
            },
            {
                '_id': 'mock_030',
                'id': 'mock_030',
                'titulo_oferta': 'Técnico en Seguridad',
                'empresa': 'Seguridad Integral Tacna',
                'nivel_academico': 'Bachiller',
                'puesto': 'Técnico en Seguridad',
                'experiencia_minima_anios': '1 año',
                'conocimientos_clave': 'seguridad, sistemas de alarmas, cámaras, vigilancia',
                'responsabilidades_breve': 'Instalación de sistemas de seguridad, mantenimiento de equipos, monitoreo, atención a clientes.',
                'modalidad': 'Presencial',
                'ubicacion': 'Tacna',
                'jornada': 'Tiempo completo',
                'salario': 'S/ 1,500 - S/ 1,800',
                'fecha_publicacion': (fecha_base - timedelta(days=27)).strftime('%Y-%m-%d'),
                'fecha_cierre': None,
                'como_postular': 'Postular en: https://www.trabajos.pe/oferta/030',
                'url_oferta': 'https://www.trabajos.pe/oferta/030',
                'documentos_requeridos': 'CV, certificados',
                'contacto': 'rrhh@seguridadintegral.com',
                'etiquetas': 'trabajos.pe, tacna, seguridad, técnico',
                'fuente': 'Trabajos.pe',
                'fecha_estimacion': False,
                'created_at': (fecha_base - timedelta(days=27)).isoformat(),
                'updated_at': (fecha_base - timedelta(days=26)).isoformat()
            }
        ]
    
    @staticmethod
    def get_mock_estadisticas() -> Dict:
        """Retorna estadísticas simuladas en el formato esperado por el dashboard"""
        return {
            'total_ofertas': 30,
            'por_nivel': {
                'Profesional': 12,
                'Bachiller': 16,
                'Practicante': 2
            },
            'por_modalidad': {
                'Presencial': 18,
                'Remoto': 4,
                'Híbrido': 8
            },
            'por_fuente': {
                'Computrabajo': 8,
                'Bumeran': 8,
                'Indeed': 7,
                'Trabajos.pe': 7
            },
            'top_empresas': {
                'Tech Solutions Tacna': 1,
                'Empresa Comercial Tacna S.A.C.': 1,
                'Sistema Informático Regional': 1,
                'Estudio Contable Tacna': 1,
                'Agencia Creativa Tacna': 1,
                'Clínica San José Tacna': 1,
                'Tienda Retail Tacna': 1,
                'Empresa Tecnológica Tacna': 1,
                'Consultora RRHH Tacna': 1,
                'Agencia Digital Tacna': 1,
                'Corporación Tecnológica del Sur': 1,
                'Supermercado El Ahorro': 1,
                'Constructora Tacna S.A.': 1,
                'Oficina Legal Tacna': 1,
                'Startup Tech Tacna': 1
            }
        }
    
    @staticmethod
    def get_mock_usuario() -> Dict:
        """Retorna un usuario mock para modo offline"""
        return {
            '_id': 'mock_user_001',
            'id': 'mock_user_001',
            'username': 'admin',
            'email': 'admin@ofertas.com',
            'is_active': True,
            'created_at': datetime.now().isoformat()
        }
    
    @staticmethod
    def filter_ofertas(ofertas: List[Dict], filtros: Dict = None) -> List[Dict]:
        """Filtra ofertas mock según los criterios proporcionados"""
        if not filtros:
            return ofertas
        
        filtered = ofertas
        
        # Filtro por empresa
        if filtros.get('empresa'):
            empresa_filter = filtros['empresa'].lower()
            filtered = [o for o in filtered if empresa_filter in o.get('empresa', '').lower()]
        
        # Filtro por nivel académico
        if filtros.get('nivel_academico'):
            filtered = [o for o in filtered if o.get('nivel_academico') == filtros['nivel_academico']]
        
        # Filtro por modalidad
        if filtros.get('modalidad'):
            filtered = [o for o in filtered if o.get('modalidad') == filtros['modalidad']]
        
        # Búsqueda de texto
        if filtros.get('busqueda'):
            busqueda = filtros['busqueda'].lower()
            filtered = [o for o in filtered if (
                busqueda in o.get('titulo_oferta', '').lower() or
                busqueda in o.get('empresa', '').lower() or
                busqueda in o.get('puesto', '').lower() or
                busqueda in o.get('conocimientos_clave', '').lower()
            )]
        
        return filtered

